### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by amelie88** [QuetzalMX/QuetzalXLSReader#3]
Hi Olivares

I am trying to use this library in my project, but can not get it to work.

I have added the library to my frameworks, and in viewDidLoad in my first view I have added

NSURL *url = [[NSURL alloc] initWithString:@"Transactions.xls"];

```
QZWorkbook *excelReader = [[QZWorkbook alloc] initWithContentsOfXLS:url];

QZWorkSheet *firstWorkSheet = excelReader.workSheets.firstObject;
[firstWorkSheet open];

NSLog(@"%@", firstWorkSheet.rows.firstObject);
```

I have included the library in my .h file.

But the output from my NSLog is (null).

What am I missing? 

Any help would be greatly appreciated!

**Comment by silviu-geronimo** [comment]
I know this is super outdated but you could solve your problem using this way to get the url after dragged and dropped your excel file into the project tree:

```
NSURL *urlPath = [[NSBundle mainBundle]
                    URLForResource: @"Historico" withExtension:@"xls"];
QZWorkbook *excelReader = [[QZWorkbook alloc] initWithContentsOfXLS:urlPath];
```

**Comment by guiltm** [comment]
A little outdated ^^
I solved in the season, but thanks for attention,

2016-09-21 7:55 GMT-03:00 silviu-geronimo notifications@github.com:
